# Generated by Django 4.1.5 on 2023-01-16 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_newscreated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newscreated',
            name='date',
            field=models.DateField(),
        ),
    ]
